[2025-04-20 17:53:49,561]: [ dispatcher ][ (func name: _process_update line 315 ) ] #ERROR : aiogram.event        -  Cause exception while process update id=52146949 by bot id=8059818753
ChannelNotFoundEntity: NOT_FOUND - no exchange 'message_delete_exchanger' in vhost '/'
Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\abc.py", line 44, in __inner
    return await self.task
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\channel.py", line 453, in _reader
    await self.close(
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\base.py", line 141, in close
    await countdown(self.__closer(exc))
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\tools.py", line 96, in __call__
    return await asyncio.wait_for(coro, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\base.py", line 131, in __closer
    await self._cancel_tasks(exc)
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 684, in _wrap_awaitable
    return await awaitable
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\abc.py", line 46, in __inner
    raise self._exception from e
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\track_msg.py", line 25, in __call__
    handler = await handler(custom_message, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\handlers\default_mode.py", line 25, in cancel_process_handler
    await message.answer("Canceled")
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\custom_types\messages.py", line 9, in answer
    await callback(answer.chat.id, answer.message_id)
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\services\delete_msg_service.py", line 17, in track_message
    await self.broker.publish_message(message)
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\clients\RabbitMq.py", line 36, in publish_message
    await channel.basic_publish(
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\channel.py", line 699, in basic_publish
    return await countdown(confirmation)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\tools.py", line 95, in __call__
    return await coro
           ^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\channel.py", line 441, in _reader
    await hook(frame)
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\channel.py", line 410, in _on_close_frame
    raise exc
aiormq.exceptions.ChannelNotFoundEntity: NOT_FOUND - no exchange 'message_delete_exchanger' in vhost '/'
[2025-04-20 17:53:49,561]: [ dispatcher ][ (func name: _process_update line 315 ) ] #ERROR : aiogram.event        -  Cause exception while process update id=52146949 by bot id=8059818753
ChannelNotFoundEntity: NOT_FOUND - no exchange 'message_delete_exchanger' in vhost '/'
Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\abc.py", line 44, in __inner
    return await self.task
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\channel.py", line 453, in _reader
    await self.close(
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\base.py", line 141, in close
    await countdown(self.__closer(exc))
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\tools.py", line 96, in __call__
    return await asyncio.wait_for(coro, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\base.py", line 131, in __closer
    await self._cancel_tasks(exc)
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 684, in _wrap_awaitable
    return await awaitable
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\abc.py", line 46, in __inner
    raise self._exception from e
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\track_msg.py", line 25, in __call__
    handler = await handler(custom_message, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\handlers\default_mode.py", line 25, in cancel_process_handler
    await message.answer("Canceled")
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\custom_types\messages.py", line 9, in answer
    await callback(answer.chat.id, answer.message_id)
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\services\delete_msg_service.py", line 17, in track_message
    await self.broker.publish_message(message)
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\clients\RabbitMq.py", line 36, in publish_message
    await channel.basic_publish(
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\channel.py", line 699, in basic_publish
    return await countdown(confirmation)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\tools.py", line 95, in __call__
    return await coro
           ^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\channel.py", line 441, in _reader
    await hook(frame)
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\channel.py", line 410, in _on_close_frame
    raise exc
aiormq.exceptions.ChannelNotFoundEntity: NOT_FOUND - no exchange 'message_delete_exchanger' in vhost '/'
[2025-04-20 17:54:10,022]: [ dispatcher ][ (func name: _process_update line 315 ) ] #ERROR : aiogram.event        -  Cause exception while process update id=52146950 by bot id=8059818753
ChannelNotFoundEntity: NOT_FOUND - no exchange 'message_delete_exchanger' in vhost '/'
Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\abc.py", line 44, in __inner
    return await self.task
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\channel.py", line 453, in _reader
    await self.close(
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\base.py", line 141, in close
    await countdown(self.__closer(exc))
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\tools.py", line 96, in __call__
    return await asyncio.wait_for(coro, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\base.py", line 131, in __closer
    await self._cancel_tasks(exc)
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 684, in _wrap_awaitable
    return await awaitable
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\abc.py", line 46, in __inner
    raise self._exception from e
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\track_msg.py", line 25, in __call__
    handler = await handler(custom_message, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\handlers\default_mode.py", line 25, in cancel_process_handler
    await message.answer("Canceled")
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\custom_types\messages.py", line 9, in answer
    await callback(answer.chat.id, answer.message_id)
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\services\delete_msg_service.py", line 17, in track_message
    await self.broker.publish_message(message)
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\clients\RabbitMq.py", line 36, in publish_message
    await channel.basic_publish(
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\channel.py", line 699, in basic_publish
    return await countdown(confirmation)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\tools.py", line 95, in __call__
    return await coro
           ^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\channel.py", line 441, in _reader
    await hook(frame)
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\channel.py", line 410, in _on_close_frame
    raise exc
aiormq.exceptions.ChannelNotFoundEntity: NOT_FOUND - no exchange 'message_delete_exchanger' in vhost '/'
[2025-04-20 17:54:10,022]: [ dispatcher ][ (func name: _process_update line 315 ) ] #ERROR : aiogram.event        -  Cause exception while process update id=52146950 by bot id=8059818753
ChannelNotFoundEntity: NOT_FOUND - no exchange 'message_delete_exchanger' in vhost '/'
Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\abc.py", line 44, in __inner
    return await self.task
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\channel.py", line 453, in _reader
    await self.close(
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\base.py", line 141, in close
    await countdown(self.__closer(exc))
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\tools.py", line 96, in __call__
    return await asyncio.wait_for(coro, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\base.py", line 131, in __closer
    await self._cancel_tasks(exc)
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 684, in _wrap_awaitable
    return await awaitable
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\abc.py", line 46, in __inner
    raise self._exception from e
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\track_msg.py", line 25, in __call__
    handler = await handler(custom_message, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\handlers\default_mode.py", line 25, in cancel_process_handler
    await message.answer("Canceled")
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\custom_types\messages.py", line 9, in answer
    await callback(answer.chat.id, answer.message_id)
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\services\delete_msg_service.py", line 17, in track_message
    await self.broker.publish_message(message)
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\clients\RabbitMq.py", line 36, in publish_message
    await channel.basic_publish(
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\channel.py", line 699, in basic_publish
    return await countdown(confirmation)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\tools.py", line 95, in __call__
    return await coro
           ^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\channel.py", line 441, in _reader
    await hook(frame)
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\channel.py", line 410, in _on_close_frame
    raise exc
aiormq.exceptions.ChannelNotFoundEntity: NOT_FOUND - no exchange 'message_delete_exchanger' in vhost '/'
[2025-04-20 17:55:37,740]: [ dispatcher ][ (func name: _process_update line 315 ) ] #ERROR : aiogram.event        -  Cause exception while process update id=52146951 by bot id=8059818753
ChannelNotFoundEntity: NOT_FOUND - no exchange 'message_delete_exchanger' in vhost '/'
Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\abc.py", line 44, in __inner
    return await self.task
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\channel.py", line 453, in _reader
    await self.close(
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\base.py", line 141, in close
    await countdown(self.__closer(exc))
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\tools.py", line 96, in __call__
    return await asyncio.wait_for(coro, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\base.py", line 131, in __closer
    await self._cancel_tasks(exc)
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 684, in _wrap_awaitable
    return await awaitable
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\abc.py", line 46, in __inner
    raise self._exception from e
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\track_msg.py", line 25, in __call__
    handler = await handler(custom_message, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\handlers\default_mode.py", line 25, in cancel_process_handler
    await message.answer("Canceled")
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\custom_types\messages.py", line 9, in answer
    await callback(answer.chat.id, answer.message_id)
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\services\delete_msg_service.py", line 17, in track_message
    await self.broker.publish_message(message)
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\clients\RabbitMq.py", line 36, in publish_message
    await channel.basic_publish(
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\channel.py", line 699, in basic_publish
    return await countdown(confirmation)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\tools.py", line 95, in __call__
    return await coro
           ^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\channel.py", line 441, in _reader
    await hook(frame)
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\channel.py", line 410, in _on_close_frame
    raise exc
aiormq.exceptions.ChannelNotFoundEntity: NOT_FOUND - no exchange 'message_delete_exchanger' in vhost '/'
[2025-04-20 17:55:37,740]: [ dispatcher ][ (func name: _process_update line 315 ) ] #ERROR : aiogram.event        -  Cause exception while process update id=52146951 by bot id=8059818753
ChannelNotFoundEntity: NOT_FOUND - no exchange 'message_delete_exchanger' in vhost '/'
Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\abc.py", line 44, in __inner
    return await self.task
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\channel.py", line 453, in _reader
    await self.close(
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\base.py", line 141, in close
    await countdown(self.__closer(exc))
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\tools.py", line 96, in __call__
    return await asyncio.wait_for(coro, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\base.py", line 131, in __closer
    await self._cancel_tasks(exc)
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 684, in _wrap_awaitable
    return await awaitable
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\abc.py", line 46, in __inner
    raise self._exception from e
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\track_msg.py", line 25, in __call__
    handler = await handler(custom_message, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\handlers\default_mode.py", line 25, in cancel_process_handler
    await message.answer("Canceled")
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\custom_types\messages.py", line 9, in answer
    await callback(answer.chat.id, answer.message_id)
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\services\delete_msg_service.py", line 17, in track_message
    await self.broker.publish_message(message)
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\clients\RabbitMq.py", line 36, in publish_message
    await channel.basic_publish(
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\channel.py", line 699, in basic_publish
    return await countdown(confirmation)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\tools.py", line 95, in __call__
    return await coro
           ^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\channel.py", line 441, in _reader
    await hook(frame)
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiormq\channel.py", line 410, in _on_close_frame
    raise exc
aiormq.exceptions.ChannelNotFoundEntity: NOT_FOUND - no exchange 'message_delete_exchanger' in vhost '/'
[2025-04-20 19:12:59,956]: [ dispatcher ][ (func name: _process_update line 315 ) ] #ERROR : aiogram.event        -  Cause exception while process update id=52147019 by bot id=8059818753
ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=<fluentogram.src.impl.run...t at 0x0000016BFE2B17F0>, input_type=TranslatorRunner]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\track_msg.py", line 25, in __call__
    handler = await handler(custom_message, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\i18n.py", line 19, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\handlers\default_mode.py", line 25, in cancel_process_handler
    await message.answer(i18n.message.text)
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\custom_types\messages.py", line 6, in answer
    answer = await super().answer(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\types\message.py", line 2074, in answer
    return SendMessage(
           ^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\pydantic\main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=<fluentogram.src.impl.run...t at 0x0000016BFE2B17F0>, input_type=TranslatorRunner]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
[2025-04-20 19:12:59,956]: [ dispatcher ][ (func name: _process_update line 315 ) ] #ERROR : aiogram.event        -  Cause exception while process update id=52147019 by bot id=8059818753
ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=<fluentogram.src.impl.run...t at 0x0000016BFE2B17F0>, input_type=TranslatorRunner]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\track_msg.py", line 25, in __call__
    handler = await handler(custom_message, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\i18n.py", line 19, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\handlers\default_mode.py", line 25, in cancel_process_handler
    await message.answer(i18n.message.text)
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\custom_types\messages.py", line 6, in answer
    answer = await super().answer(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\types\message.py", line 2074, in answer
    return SendMessage(
           ^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\pydantic\main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=<fluentogram.src.impl.run...t at 0x0000016BFE2B17F0>, input_type=TranslatorRunner]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
[2025-04-20 19:12:59,996]: [ dispatcher ][ (func name: _process_update line 315 ) ] #ERROR : aiogram.event        -  Cause exception while process update id=52147018 by bot id=8059818753
ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=<fluentogram.src.impl.run...t at 0x0000016B813C1FD0>, input_type=TranslatorRunner]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\track_msg.py", line 25, in __call__
    handler = await handler(custom_message, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\i18n.py", line 19, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\handlers\default_mode.py", line 25, in cancel_process_handler
    await message.answer(i18n.message.text)
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\custom_types\messages.py", line 6, in answer
    answer = await super().answer(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\types\message.py", line 2074, in answer
    return SendMessage(
           ^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\pydantic\main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=<fluentogram.src.impl.run...t at 0x0000016B813C1FD0>, input_type=TranslatorRunner]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
[2025-04-20 19:12:59,996]: [ dispatcher ][ (func name: _process_update line 315 ) ] #ERROR : aiogram.event        -  Cause exception while process update id=52147018 by bot id=8059818753
ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=<fluentogram.src.impl.run...t at 0x0000016B813C1FD0>, input_type=TranslatorRunner]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\track_msg.py", line 25, in __call__
    handler = await handler(custom_message, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\i18n.py", line 19, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\handlers\default_mode.py", line 25, in cancel_process_handler
    await message.answer(i18n.message.text)
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\custom_types\messages.py", line 6, in answer
    answer = await super().answer(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\types\message.py", line 2074, in answer
    return SendMessage(
           ^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\pydantic\main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=<fluentogram.src.impl.run...t at 0x0000016B813C1FD0>, input_type=TranslatorRunner]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
[2025-04-20 19:13:30,258]: [ dispatcher ][ (func name: _listen_updates line 219 ) ] #ERROR : aiogram.dispatcher   -  Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [Errno 1] [SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2685)
[2025-04-20 19:13:30,258]: [ dispatcher ][ (func name: _listen_updates line 219 ) ] #ERROR : aiogram.dispatcher   -  Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [Errno 1] [SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2685)
[2025-04-20 19:13:38,392]: [ dispatcher ][ (func name: _process_update line 315 ) ] #ERROR : aiogram.event        -  Cause exception while process update id=52147020 by bot id=8059818753
ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=<fluentogram.src.impl.run...t at 0x0000015DD86DEF60>, input_type=TranslatorRunner]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\track_msg.py", line 25, in __call__
    handler = await handler(custom_message, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\i18n.py", line 19, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\handlers\default_mode.py", line 25, in cancel_process_handler
    await message.answer(i18n.message.text)
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\custom_types\messages.py", line 6, in answer
    answer = await super().answer(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\types\message.py", line 2074, in answer
    return SendMessage(
           ^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\pydantic\main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=<fluentogram.src.impl.run...t at 0x0000015DD86DEF60>, input_type=TranslatorRunner]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
[2025-04-20 19:13:38,392]: [ dispatcher ][ (func name: _process_update line 315 ) ] #ERROR : aiogram.event        -  Cause exception while process update id=52147020 by bot id=8059818753
ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=<fluentogram.src.impl.run...t at 0x0000015DD86DEF60>, input_type=TranslatorRunner]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\track_msg.py", line 25, in __call__
    handler = await handler(custom_message, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\i18n.py", line 19, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\handlers\default_mode.py", line 25, in cancel_process_handler
    await message.answer(i18n.message.text)
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\custom_types\messages.py", line 6, in answer
    answer = await super().answer(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\types\message.py", line 2074, in answer
    return SendMessage(
           ^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\pydantic\main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=<fluentogram.src.impl.run...t at 0x0000015DD86DEF60>, input_type=TranslatorRunner]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
[2025-04-20 19:14:18,368]: [ dispatcher ][ (func name: _process_update line 315 ) ] #ERROR : aiogram.event        -  Cause exception while process update id=52147021 by bot id=8059818753
ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\track_msg.py", line 25, in __call__
    handler = await handler(custom_message, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\i18n.py", line 19, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\handlers\default_mode.py", line 25, in cancel_process_handler
    await message.answer(i18n.message.text())
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\custom_types\messages.py", line 6, in answer
    answer = await super().answer(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\types\message.py", line 2074, in answer
    return SendMessage(
           ^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\pydantic\main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
[2025-04-20 19:14:18,368]: [ dispatcher ][ (func name: _process_update line 315 ) ] #ERROR : aiogram.event        -  Cause exception while process update id=52147021 by bot id=8059818753
ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\track_msg.py", line 25, in __call__
    handler = await handler(custom_message, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\i18n.py", line 19, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\handlers\default_mode.py", line 25, in cancel_process_handler
    await message.answer(i18n.message.text())
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\custom_types\messages.py", line 6, in answer
    answer = await super().answer(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\types\message.py", line 2074, in answer
    return SendMessage(
           ^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\pydantic\main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
[2025-04-20 19:14:33,132]: [ dispatcher ][ (func name: _process_update line 315 ) ] #ERROR : aiogram.event        -  Cause exception while process update id=52147022 by bot id=8059818753
ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\track_msg.py", line 25, in __call__
    handler = await handler(custom_message, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\i18n.py", line 19, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\handlers\default_mode.py", line 25, in cancel_process_handler
    await message.answer(i18n.message.text())
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\custom_types\messages.py", line 6, in answer
    answer = await super().answer(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\types\message.py", line 2074, in answer
    return SendMessage(
           ^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\pydantic\main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
[2025-04-20 19:14:33,132]: [ dispatcher ][ (func name: _process_update line 315 ) ] #ERROR : aiogram.event        -  Cause exception while process update id=52147022 by bot id=8059818753
ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\track_msg.py", line 25, in __call__
    handler = await handler(custom_message, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\i18n.py", line 19, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\handlers\default_mode.py", line 25, in cancel_process_handler
    await message.answer(i18n.message.text())
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\custom_types\messages.py", line 6, in answer
    answer = await super().answer(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\types\message.py", line 2074, in answer
    return SendMessage(
           ^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\pydantic\main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
[2025-04-20 19:17:28,216]: [ dispatcher ][ (func name: _process_update line 315 ) ] #ERROR : aiogram.event        -  Cause exception while process update id=52147023 by bot id=8059818753
ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\track_msg.py", line 25, in __call__
    handler = await handler(custom_message, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\i18n.py", line 20, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\handlers\default_mode.py", line 25, in cancel_process_handler
    await message.answer(i18n.message.text())
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\custom_types\messages.py", line 6, in answer
    answer = await super().answer(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\types\message.py", line 2074, in answer
    return SendMessage(
           ^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\pydantic\main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
[2025-04-20 19:17:28,216]: [ dispatcher ][ (func name: _process_update line 315 ) ] #ERROR : aiogram.event        -  Cause exception while process update id=52147023 by bot id=8059818753
ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\track_msg.py", line 25, in __call__
    handler = await handler(custom_message, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\i18n.py", line 20, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\handlers\default_mode.py", line 25, in cancel_process_handler
    await message.answer(i18n.message.text())
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\custom_types\messages.py", line 6, in answer
    answer = await super().answer(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\types\message.py", line 2074, in answer
    return SendMessage(
           ^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\pydantic\main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
[2025-04-20 19:18:02,708]: [ dispatcher ][ (func name: _process_update line 315 ) ] #ERROR : aiogram.event        -  Cause exception while process update id=52147024 by bot id=8059818753
ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\track_msg.py", line 25, in __call__
    handler = await handler(custom_message, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\i18n.py", line 20, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\handlers\default_mode.py", line 25, in cancel_process_handler
    await message.answer(i18n.message.text())
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\custom_types\messages.py", line 6, in answer
    answer = await super().answer(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\types\message.py", line 2074, in answer
    return SendMessage(
           ^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\pydantic\main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
[2025-04-20 19:18:02,708]: [ dispatcher ][ (func name: _process_update line 315 ) ] #ERROR : aiogram.event        -  Cause exception while process update id=52147024 by bot id=8059818753
ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\track_msg.py", line 25, in __call__
    handler = await handler(custom_message, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\i18n.py", line 20, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\handlers\default_mode.py", line 25, in cancel_process_handler
    await message.answer(i18n.message.text())
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\custom_types\messages.py", line 6, in answer
    answer = await super().answer(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\types\message.py", line 2074, in answer
    return SendMessage(
           ^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\pydantic\main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
[2025-04-20 19:18:51,245]: [ dispatcher ][ (func name: _process_update line 315 ) ] #ERROR : aiogram.event        -  Cause exception while process update id=52147025 by bot id=8059818753
ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\track_msg.py", line 25, in __call__
    handler = await handler(custom_message, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\i18n.py", line 20, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\handlers\default_mode.py", line 26, in cancel_process_handler
    await message.answer(i18n.message())
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\custom_types\messages.py", line 6, in answer
    answer = await super().answer(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\types\message.py", line 2074, in answer
    return SendMessage(
           ^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\pydantic\main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
[2025-04-20 19:18:51,245]: [ dispatcher ][ (func name: _process_update line 315 ) ] #ERROR : aiogram.event        -  Cause exception while process update id=52147025 by bot id=8059818753
ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
Traceback (most recent call last):
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\storage.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\track_msg.py", line 25, in __call__
    handler = await handler(custom_message, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\middlewares\i18n.py", line 20, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\handlers\default_mode.py", line 26, in cancel_process_handler
    await message.answer(i18n.message())
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\custom_types\messages.py", line 6, in answer
    answer = await super().answer(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\aiogram\types\message.py", line 2074, in answer
    return SendMessage(
           ^^^^^^^^^^^^
  File "D:\PyCharm\PythonProjects\Stepik TeleBot\TeleBot XaBaYaBa v3\.venv\Lib\site-packages\pydantic\main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
